# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b186d26a82ae0a6ebbc0244370bd9a661ee353aa0a78cdeac3d4fdc08b4992209d8dd8a0294832be1fdb93d98d7c6c62071007d5f1a342aa2b68741ae4e7dcc

test:
  secret_key_base: 7f936947d3c6cc22dbd47f2cce73db3dedf3625427bc947770ecf7e9d525dfdf5ddabf7e914b4aea63ee2db899992243b17131c614bb00cedafb155399e648c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
